### ISSUE TITLE
Correct app download check feature

### ISSUE THREAD

**Issue by sthakrishnakumar** [devamitkumartiwari/devicesafetyinfo#1]
Can check that the app is installed through the correct content service (such as Google Play or Apple Store).
This feature is provided by flutter_security_checker ( https://pub.dev/packages/flutter_security_checker ).

**Comment by amitkumartiwaridis** [comment]
No, currently this package does not have this feature, but in the future will try to add this one also.

> Can check that the app is installed through the correct content service (such as Google Play or Apple Store). This feature is provided by flutter_security_checker ( https://pub.dev/packages/flutter_security_checker ).

**Comment by sthakrishnakumar** [comment]
Hoping to get that feature included
